Fix bug navbar
WildCodeSchool/0322_P3_Php_Lyon_Irep pull request #12
Opened 2023-06-07 13:16 UTC by Mouhamed114

2023-06-07 13:20 UTC, MisterPingouin requested changes
Menu in french and no dead link.

2023-06-07 13:48 UTC, aldaitzwild approved these changes

2023-06-07 14:55 UTC, aldaitzwild requested changes

2023-06-07 14:55 UTC, aldaitzwild commented on assets/styles/app.scss
> +<<<<<<< HEAD
Unresolved conflict

2023-06-07 14:55 UTC, aldaitzwild commented on assets/styles/app.scss
> +=======
Unresolved conflict

2023-06-07 14:55 UTC, aldaitzwild commented on assets/styles/app.scss
> +>>>>>>> de1ac5598a869ef8f911279644d8cd4326a2811d
Unresolved conflict

2023-06-07 14:55 UTC, aldaitzwild commented on templates/includes/_navbar.html.twig
> +<<<<<<< HEAD
Unresolved conflict

2023-06-07 14:55 UTC, aldaitzwild commented on templates/includes/_navbar.html.twig
> +=======
Unresolved conflict

2023-06-07 14:55 UTC, aldaitzwild commented on templates/includes/_navbar.html.twig
> +>>>>>>> de1ac5598a869ef8f911279644d8cd4326a2811d
Unresolved conflict

2023-06-08 07:13 UTC, aldaitzwild requested changes

2023-06-08 07:13 UTC, aldaitzwild commented on migrations/Version20230607144737.php
> +        $this->addSql('CREATE TABLE messenger_messages (id BIGINT AUTO_INCREMENT NOT NULL, body LONGTEXT NOT NULL, headers LONGTEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at DATETIME NOT
Why do you have a migration when you don't work on the entities ?

2023-06-08 08:43 UTC, aldaitzwild requested changes

2023-06-08 08:43 UTC, aldaitzwild commented on assets/styles/app.scss
> +.custum-bg-color-burger-menu{
I guess you wanted to write "custom" right ?

2023-06-08 09:38 UTC, aldaitzwild requested changes

2023-06-08 09:38 UTC, aldaitzwild commented on templates/includes/_navbar.html.twig
> +          <a href="{{ path('app_picture_index') }}" class="custum-bg-color-burger-menu block py-2 pl-3 pr-4 text-white rounded dark:bg-blue-600" aria-current="page">Galerie</a>
Still "custum" ?

2023-06-08 12:13 UTC, aldaitzwild approved these changes

2023-06-08 12:13 UTC, merged