S 02 17 donner la possibilité dans la galerie de ne pas afficher uniquement en mosaïque
WildCodeSchool/0322_P3_Php_Lyon_Irep pull request #23
Opened 2023-06-09 21:10 UTC by MisterPingouin

2023-06-11 19:58 UTC, Mouhamed114 approved these changes

2023-06-13 06:50 UTC, aldaitzwild requested changes

2023-06-13 06:50 UTC, aldaitzwild commented on assets/galery.js
> +        let testImg = new Image();
It would be nice to name it properly, wouldn't be ?

2023-06-13 13:21 UTC, aldaitzwild approved these changes

2023-06-13 13:21 UTC, merged