S 02 28 page galery optimisation
WildCodeSchool/0322_P3_Php_Lyon_Irep pull request #33
Opened 2023-06-14 14:08 UTC by MisterPingouin

2023-06-14 15:25 UTC, lbf-2974 requested changes
assets/styles/galery.scss
* class .bullet has to be written with tailwind

2023-06-14 20:07 UTC, lbf-2974 approved these changes

2023-06-15 07:28 UTC, aldaitzwild requested changes

2023-06-15 07:28 UTC, aldaitzwild commented on assets/styles/galery.scss
> +}
Is this class still usefull ?

2023-06-15 07:44 UTC, MisterPingouin commented on assets/styles/galery.scss
> +}
Yes it is, as the class is created by the Javascript code in galery.js, i think it's the best way to apply the style on this class because if i put it in tailwind class in the template it will not be affected.
Maybe there is an other way, but i can't think of a better one.

2023-06-15 12:08 UTC, aldaitzwild approved these changes

2023-06-15 12:08 UTC, merged