S02 19 page dadmin liste des exposition
WildCodeSchool/0322_P3_Php_Lyon_Irep pull request #34
Opened 2023-06-14 19:41 UTC by MisterPingouin

2023-06-14 22:46 UTC, Mouhamed114 approved these changes

2023-06-15 08:36 UTC, aldaitzwild requested changes

2023-06-15 08:36 UTC, aldaitzwild commented on src/Controller/HomeController.php
> +        $presexhibition = $presexhibition->findAll();
No.

First name your repository clearly.
Then do not override a repository with a collection returned by it => create a new variable, it's really not that expensive ...

2023-06-15 09:27 UTC, aldaitzwild requested changes

2023-06-15 09:27 UTC, aldaitzwild commented on src/Entity/PresentationExhibition.php
> +    private ?Exhibition $exhibitionId = null;
Why is this named exhibitionId when it is not an id stored here ?

2023-06-15 12:12 UTC, aldaitzwild approved these changes

2023-06-15 12:12 UTC, merged