S 06 fix gallery on exposition
WildCodeSchool/0322_P3_Php_Lyon_Irep pull request #51
Opened 2023-07-11 11:38 UTC by MisterPingouin

2023-07-11 11:59 UTC, Mouhamed114 approved these changes

2023-07-11 12:32 UTC, aldaitzwild requested changes

2023-07-11 12:32 UTC, aldaitzwild commented on src/Controller/PictureController.php
> +        $exhibitionId = $request->query->get('exhibition');
No you should pass the id of the exhibition through the route "/{id}" and directly get an exhibition from the action parameters.

2023-07-11 12:32 UTC, aldaitzwild commented on src/Controller/PictureController.php
> +         : $pictureRepository->findAll();
No ! You won't do a findAll() if you don't the right exhibition !! If do that you'll see every picture from every exhibition even the closed ones

2023-07-12 09:57 UTC, aldaitzwild requested changes

2023-07-12 09:57 UTC, aldaitzwild commented on src/Controller/PictureController.php
> +        $exhibition = $exhibitionRepository->find($id);
No you should ask symfony to give you the exhibition thanks to the id => https://symfony.com/doc/current/doctrine.html#automatically-fetching-objects-entityvalueresolver

2023-07-12 09:57 UTC, aldaitzwild commented on src/Controller/PictureController.php
> +        $exhibition = $exhibitionRepository->find($id);
Still there

2023-07-12 10:14 UTC, aldaitzwild approved these changes

2023-07-12 10:14 UTC, merged